[2023-11-08T17:47:58.012-0500] {processor.py:157} INFO - Started process (PID=48946) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:47:58.016-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T17:47:58.016-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:47:58.016-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:47:58.046-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:47:58.045-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T17:47:58.046-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:47:58.046-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T17:47:58.046-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:47:58.108-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2023-11-08T17:49:31.501-0500] {processor.py:157} INFO - Started process (PID=49080) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:49:31.506-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T17:49:31.506-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:49:31.506-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:49:31.536-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:49:31.535-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T17:49:31.536-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:49:31.536-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T17:49:31.536-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:49:31.600-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-08T17:51:32.177-0500] {processor.py:157} INFO - Started process (PID=49282) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:51:32.182-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T17:51:32.182-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:51:32.182-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:51:32.211-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:51:32.211-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T17:51:32.211-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:51:32.211-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T17:51:32.211-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:51:32.274-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T17:53:24.253-0500] {processor.py:157} INFO - Started process (PID=49426) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:53:24.257-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T17:53:24.258-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:53:24.258-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:53:24.287-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:53:24.286-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T17:53:24.287-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:53:24.287-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T17:53:24.287-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:53:24.350-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T17:55:22.044-0500] {processor.py:157} INFO - Started process (PID=49572) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:55:22.049-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T17:55:22.049-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:55:22.049-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:55:22.079-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:55:22.078-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T17:55:22.079-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:55:22.079-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T17:55:22.079-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:55:22.141-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T17:57:22.267-0500] {processor.py:157} INFO - Started process (PID=49723) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:57:22.272-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T17:57:22.272-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:57:22.272-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:57:22.302-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:57:22.302-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T17:57:22.303-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:57:22.303-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T17:57:22.303-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:57:22.366-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-08T17:59:23.565-0500] {processor.py:157} INFO - Started process (PID=49891) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:59:23.569-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T17:59:23.570-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:59:23.570-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:59:23.599-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:59:23.599-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T17:59:23.599-0500] {logging_mixin.py:154} INFO - [2023-11-08T17:59:23.599-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T17:59:23.599-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T17:59:23.662-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T18:01:24.440-0500] {processor.py:157} INFO - Started process (PID=50057) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:01:24.445-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:01:24.445-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:01:24.445-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:01:24.484-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:01:24.484-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:01:24.484-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:01:24.484-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:01:24.484-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:01:24.556-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2023-11-08T18:03:21.601-0500] {processor.py:157} INFO - Started process (PID=50261) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:03:21.605-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:03:21.606-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:03:21.606-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:03:21.636-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:03:21.635-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:03:21.636-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:03:21.636-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:03:21.636-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:03:21.702-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2023-11-08T18:05:18.010-0500] {processor.py:157} INFO - Started process (PID=50534) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:05:18.016-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:05:18.016-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:05:18.016-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:05:18.045-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:05:18.045-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:05:18.045-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:05:18.045-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:05:18.045-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:05:18.108-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-08T18:07:12.613-0500] {processor.py:157} INFO - Started process (PID=50690) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:07:12.617-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:07:12.617-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:07:12.617-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:07:12.646-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:07:12.646-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:07:12.646-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:07:12.646-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:07:12.646-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:07:12.709-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2023-11-08T18:09:09.057-0500] {processor.py:157} INFO - Started process (PID=50855) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:09:09.062-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:09:09.062-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:09:09.062-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:09:09.092-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:09:09.091-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:09:09.092-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:09:09.092-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:09:09.092-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:09:09.154-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-08T18:11:09.023-0500] {processor.py:157} INFO - Started process (PID=51010) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:11:09.027-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:11:09.027-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:11:09.027-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:11:09.056-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:11:09.056-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:11:09.056-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:11:09.056-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:11:09.056-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:11:09.119-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2023-11-08T18:23:07.552-0500] {processor.py:157} INFO - Started process (PID=51198) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:23:07.557-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:23:07.557-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:23:07.557-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:23:07.586-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:23:07.586-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:23:07.586-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:23:07.586-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:23:07.586-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:23:07.649-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T18:31:50.223-0500] {processor.py:157} INFO - Started process (PID=51343) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:31:50.228-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:31:50.228-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:31:50.228-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:31:50.256-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:31:50.256-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:31:50.257-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:31:50.256-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:31:50.257-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:31:50.319-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T18:33:55.693-0500] {processor.py:157} INFO - Started process (PID=51509) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:33:55.697-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:33:55.698-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:33:55.698-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:33:55.727-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:33:55.727-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:33:55.727-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:33:55.727-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:33:55.727-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:33:55.790-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-08T18:35:56.700-0500] {processor.py:157} INFO - Started process (PID=51658) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:35:56.704-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:35:56.704-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:35:56.704-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:35:56.733-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:35:56.733-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:35:56.733-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:35:56.733-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:35:56.733-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:35:56.796-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2023-11-08T18:37:49.699-0500] {processor.py:157} INFO - Started process (PID=51797) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:37:49.703-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:37:49.704-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:37:49.704-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:37:49.733-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:37:49.732-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:37:49.733-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:37:49.733-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:37:49.733-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:37:49.796-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-08T18:39:47.974-0500] {processor.py:157} INFO - Started process (PID=51940) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:39:47.978-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:39:47.979-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:39:47.979-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:39:48.008-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:39:48.007-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:39:48.008-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:39:48.008-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:39:48.008-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:39:48.071-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-08T18:41:52.815-0500] {processor.py:157} INFO - Started process (PID=52089) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:41:52.819-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:41:52.820-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:41:52.820-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:41:52.848-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:41:52.848-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:41:52.848-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:41:52.848-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:41:52.849-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:41:52.911-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T18:43:53.179-0500] {processor.py:157} INFO - Started process (PID=52238) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:43:53.184-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:43:53.184-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:43:53.184-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:43:53.214-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:43:53.214-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:43:53.214-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:43:53.214-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:43:53.214-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:43:53.285-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2023-11-08T18:45:56.302-0500] {processor.py:157} INFO - Started process (PID=52391) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:45:56.307-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:45:56.307-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:45:56.307-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:45:56.339-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:45:56.339-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:45:56.339-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:45:56.339-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:45:56.339-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:45:56.402-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2023-11-08T18:48:06.171-0500] {processor.py:157} INFO - Started process (PID=52604) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:48:06.175-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:48:06.176-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:48:06.176-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:48:06.205-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:48:06.205-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:48:06.205-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:48:06.205-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:48:06.205-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:48:06.268-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-08T18:50:02.915-0500] {processor.py:157} INFO - Started process (PID=52749) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:50:02.918-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:50:02.919-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:50:02.919-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:50:02.948-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:50:02.947-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:50:02.948-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:50:02.948-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:50:02.948-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:50:03.009-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2023-11-08T18:52:03.852-0500] {processor.py:157} INFO - Started process (PID=52907) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:52:03.857-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:52:03.858-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:52:03.858-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:52:03.886-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:52:03.886-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:52:03.887-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:52:03.887-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:52:03.887-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:52:03.949-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T18:54:07.321-0500] {processor.py:157} INFO - Started process (PID=53070) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:54:07.326-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:54:07.327-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:54:07.326-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:54:07.356-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:54:07.355-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:54:07.356-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:54:07.356-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:54:07.356-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:54:07.419-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-08T18:56:16.758-0500] {processor.py:157} INFO - Started process (PID=53232) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:56:16.763-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:56:16.763-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:56:16.763-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:56:16.792-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:56:16.791-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:56:16.792-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:56:16.792-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:56:16.792-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:56:16.855-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-08T18:58:20.795-0500] {processor.py:157} INFO - Started process (PID=53391) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:58:20.806-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-08T18:58:20.806-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:58:20.806-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:58:20.836-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:58:20.836-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-08T18:58:20.836-0500] {logging_mixin.py:154} INFO - [2023-11-08T18:58:20.836-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-08T18:58:20.836-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-08T18:58:20.901-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
