[2023-11-09T19:01:18.548-0500] {processor.py:157} INFO - Started process (PID=48859) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:01:18.552-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:01:18.552-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:01:18.552-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:01:18.582-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:01:18.581-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:01:18.582-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:01:18.582-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:01:18.582-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:01:18.645-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T19:03:26.389-0500] {processor.py:157} INFO - Started process (PID=49018) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:03:26.394-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:03:26.394-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:03:26.394-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:03:26.424-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:03:26.424-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:03:26.424-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:03:26.424-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:03:26.424-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:03:26.488-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:05:27.752-0500] {processor.py:157} INFO - Started process (PID=49171) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:05:27.756-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:05:27.756-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:05:27.756-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:05:27.787-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:05:27.786-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:05:27.787-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:05:27.787-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:05:27.787-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:05:27.851-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:07:27.960-0500] {processor.py:157} INFO - Started process (PID=49318) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:07:27.965-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:07:27.965-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:07:27.965-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:07:27.996-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:07:27.996-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:07:27.996-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:07:27.996-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:07:27.996-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:07:28.059-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:09:28.388-0500] {processor.py:157} INFO - Started process (PID=49464) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:09:28.393-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:09:28.393-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:09:28.393-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:09:28.423-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:09:28.423-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:09:28.423-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:09:28.423-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:09:28.424-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:09:28.487-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:11:32.887-0500] {processor.py:157} INFO - Started process (PID=49623) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:11:32.892-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:11:32.892-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:11:32.892-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:11:32.921-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:11:32.921-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:11:32.922-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:11:32.921-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:11:32.922-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:11:32.985-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:13:26.410-0500] {processor.py:157} INFO - Started process (PID=49773) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:13:26.414-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:13:26.415-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:13:26.415-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:13:26.444-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:13:26.444-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:13:26.444-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:13:26.444-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:13:26.444-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:13:26.508-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:15:23.415-0500] {processor.py:157} INFO - Started process (PID=49916) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:15:23.420-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:15:23.420-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:15:23.420-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:15:23.450-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:15:23.450-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:15:23.450-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:15:23.450-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:15:23.450-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:15:23.514-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:17:30.799-0500] {processor.py:157} INFO - Started process (PID=50070) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:17:30.804-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:17:30.804-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:17:30.804-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:17:30.834-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:17:30.834-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:17:30.834-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:17:30.834-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:17:30.835-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:17:30.898-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:19:40.706-0500] {processor.py:157} INFO - Started process (PID=50231) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:19:40.711-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:19:40.711-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:19:40.711-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:19:40.740-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:19:40.740-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:19:40.741-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:19:40.741-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:19:40.741-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:19:40.804-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:21:42.518-0500] {processor.py:157} INFO - Started process (PID=50378) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:21:42.523-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:21:42.523-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:21:42.523-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:21:42.553-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:21:42.552-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:21:42.553-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:21:42.553-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:21:42.553-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:21:42.615-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:23:58.823-0500] {processor.py:157} INFO - Started process (PID=50560) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:23:58.828-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:23:58.828-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:23:58.828-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:23:58.858-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:23:58.857-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:23:58.858-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:23:58.858-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:23:58.858-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:23:58.921-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:25:59.664-0500] {processor.py:157} INFO - Started process (PID=50708) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:25:59.669-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:25:59.669-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:25:59.669-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:25:59.703-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:25:59.702-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:25:59.703-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:25:59.703-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:25:59.703-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:25:59.767-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2023-11-09T19:28:14.289-0500] {processor.py:157} INFO - Started process (PID=50886) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:28:14.294-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:28:14.294-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:28:14.294-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:28:14.323-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:28:14.323-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:28:14.324-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:28:14.324-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:28:14.324-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:28:14.387-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:30:19.304-0500] {processor.py:157} INFO - Started process (PID=51038) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:30:19.309-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:30:19.309-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:30:19.309-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:30:19.341-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:30:19.341-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:30:19.342-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:30:19.342-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:30:19.342-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:30:19.405-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2023-11-09T19:32:25.013-0500] {processor.py:157} INFO - Started process (PID=51191) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:32:25.018-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:32:25.018-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:32:25.018-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:32:25.051-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:32:25.050-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:32:25.051-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:32:25.051-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:32:25.051-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:32:25.114-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2023-11-09T19:34:53.819-0500] {processor.py:157} INFO - Started process (PID=53211) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:34:53.824-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:34:53.825-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:34:53.824-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:34:53.854-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:34:53.854-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:34:53.854-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:34:53.854-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:34:53.855-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:34:53.918-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:36:51.058-0500] {processor.py:157} INFO - Started process (PID=53362) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:36:51.062-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:36:51.062-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:36:51.062-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:36:51.091-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:36:51.091-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:36:51.091-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:36:51.091-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:36:51.091-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:36:51.154-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2023-11-09T19:38:51.060-0500] {processor.py:157} INFO - Started process (PID=53514) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:38:51.064-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:38:51.065-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:38:51.065-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:38:51.094-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:38:51.094-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:38:51.094-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:38:51.094-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:38:51.094-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:38:51.158-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:40:47.377-0500] {processor.py:157} INFO - Started process (PID=53665) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:40:47.382-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:40:47.382-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:40:47.382-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:40:47.412-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:40:47.412-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:40:47.412-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:40:47.412-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:40:47.412-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:40:47.476-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:43:04.399-0500] {processor.py:157} INFO - Started process (PID=54126) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:43:04.404-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:43:04.404-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:43:04.404-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:43:04.434-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:43:04.433-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:43:04.434-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:43:04.434-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:43:04.434-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:43:04.498-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:45:02.422-0500] {processor.py:157} INFO - Started process (PID=54280) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:45:02.427-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:45:02.427-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:45:02.427-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:45:02.457-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:45:02.456-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:45:02.457-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:45:02.457-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:45:02.457-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:45:02.519-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:46:57.793-0500] {processor.py:157} INFO - Started process (PID=54431) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:46:57.798-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:46:57.798-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:46:57.798-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:46:57.828-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:46:57.827-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:46:57.828-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:46:57.828-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:46:57.828-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:46:57.891-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:48:58.498-0500] {processor.py:157} INFO - Started process (PID=54580) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:48:58.502-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:48:58.503-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:48:58.503-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:48:58.532-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:48:58.531-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:48:58.532-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:48:58.532-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:48:58.532-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:48:58.595-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:50:54.505-0500] {processor.py:157} INFO - Started process (PID=54729) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:50:54.510-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:50:54.510-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:50:54.510-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:50:54.540-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:50:54.540-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:50:54.540-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:50:54.540-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:50:54.540-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:50:54.604-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T19:52:54.292-0500] {processor.py:157} INFO - Started process (PID=54882) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:52:54.296-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:52:54.297-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:52:54.297-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:52:54.326-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:52:54.326-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:52:54.326-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:52:54.326-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:52:54.326-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:52:54.389-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T19:54:54.836-0500] {processor.py:157} INFO - Started process (PID=55034) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:54:54.841-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:54:54.841-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:54:54.841-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:54:54.870-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:54:54.869-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:54:54.870-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:54:54.870-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:54:54.870-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:54:54.932-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T19:56:52.278-0500] {processor.py:157} INFO - Started process (PID=55187) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:56:52.282-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:56:52.283-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:56:52.283-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:56:52.312-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:56:52.312-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:56:52.312-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:56:52.312-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:56:52.312-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:56:52.375-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T19:58:53.025-0500] {processor.py:157} INFO - Started process (PID=55344) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:58:53.029-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T19:58:53.029-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:58:53.029-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:58:53.059-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:58:53.058-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T19:58:53.059-0500] {logging_mixin.py:154} INFO - [2023-11-09T19:58:53.059-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T19:58:53.059-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T19:58:53.123-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T20:00:53.757-0500] {processor.py:157} INFO - Started process (PID=55498) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:00:53.761-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:00:53.761-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:00:53.761-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:00:53.792-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:00:53.791-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:00:53.792-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:00:53.792-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:00:53.792-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:00:53.858-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2023-11-09T20:02:55.467-0500] {processor.py:157} INFO - Started process (PID=55666) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:02:55.472-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:02:55.472-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:02:55.472-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:02:55.501-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:02:55.501-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:02:55.501-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:02:55.501-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:02:55.501-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:02:55.564-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T20:04:56.830-0500] {processor.py:157} INFO - Started process (PID=55819) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:04:56.835-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:04:56.835-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:04:56.835-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:04:56.865-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:04:56.865-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:04:56.865-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:04:56.865-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:04:56.865-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:04:56.928-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T20:06:53.629-0500] {processor.py:157} INFO - Started process (PID=55984) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:06:53.634-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:06:53.634-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:06:53.634-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:06:53.680-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:06:53.680-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:06:53.680-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:06:53.680-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:06:53.680-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:06:53.742-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2023-11-09T20:08:52.238-0500] {processor.py:157} INFO - Started process (PID=56135) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:08:52.243-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:08:52.243-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:08:52.243-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:08:52.273-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:08:52.272-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:08:52.273-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:08:52.273-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:08:52.273-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:08:52.336-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T20:10:49.233-0500] {processor.py:157} INFO - Started process (PID=56300) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:10:49.238-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:10:49.239-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:10:49.238-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:10:49.268-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:10:49.268-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:10:49.268-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:10:49.268-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:10:49.268-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:10:49.330-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T20:12:46.830-0500] {processor.py:157} INFO - Started process (PID=56466) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:12:46.834-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:12:46.835-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:12:46.835-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:12:46.864-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:12:46.864-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:12:46.864-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:12:46.864-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:12:46.864-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:12:46.927-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T20:14:47.259-0500] {processor.py:157} INFO - Started process (PID=56636) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:14:47.264-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:14:47.264-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:14:47.264-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:14:47.293-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:14:47.293-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:14:47.293-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:14:47.293-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:14:47.294-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:14:47.356-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T20:16:45.603-0500] {processor.py:157} INFO - Started process (PID=56785) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:16:45.608-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:16:45.608-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:16:45.608-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:16:45.636-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:16:45.636-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:16:45.637-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:16:45.637-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:16:45.637-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:16:45.699-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T20:18:44.451-0500] {processor.py:157} INFO - Started process (PID=56933) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:18:44.456-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:18:44.456-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:18:44.456-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:18:44.485-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:18:44.485-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:18:44.486-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:18:44.485-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:18:44.486-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:18:44.548-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T20:20:43.635-0500] {processor.py:157} INFO - Started process (PID=57081) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:20:43.640-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:20:43.640-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:20:43.640-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:20:43.672-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:20:43.671-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:20:43.672-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:20:43.672-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:20:43.672-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:20:43.735-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2023-11-09T20:22:44.584-0500] {processor.py:157} INFO - Started process (PID=57243) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:22:44.589-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:22:44.589-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:22:44.589-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:22:44.619-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:22:44.618-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:22:44.619-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:22:44.619-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:22:44.619-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:22:44.682-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T20:24:43.381-0500] {processor.py:157} INFO - Started process (PID=57393) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:24:43.385-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:24:43.385-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:24:43.385-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:24:43.414-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:24:43.414-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:24:43.415-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:24:43.414-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:24:43.415-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:24:43.477-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2023-11-09T20:26:40.413-0500] {processor.py:157} INFO - Started process (PID=57543) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:26:40.418-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:26:40.418-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:26:40.418-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:26:40.447-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:26:40.447-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:26:40.448-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:26:40.448-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:26:40.448-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:26:40.511-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T20:47:19.009-0500] {processor.py:157} INFO - Started process (PID=57860) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:47:19.014-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:47:19.014-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:47:19.014-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:47:19.044-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:47:19.044-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:47:19.044-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:47:19.044-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:47:19.044-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:47:19.108-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T20:49:16.281-0500] {processor.py:157} INFO - Started process (PID=58006) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:49:16.286-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:49:16.286-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:49:16.286-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:49:16.316-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:49:16.316-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:49:16.316-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:49:16.316-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:49:16.317-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:49:16.379-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T20:51:14.230-0500] {processor.py:157} INFO - Started process (PID=58161) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:51:14.234-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:51:14.234-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:51:14.234-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:51:14.267-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:51:14.267-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:51:14.267-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:51:14.267-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:51:14.267-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:51:14.350-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.121 seconds
[2023-11-09T20:53:21.283-0500] {processor.py:157} INFO - Started process (PID=58315) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:53:21.287-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:53:21.287-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:53:21.287-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:53:21.320-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:53:21.319-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:53:21.320-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:53:21.320-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:53:21.320-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:53:21.383-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2023-11-09T20:55:44.571-0500] {processor.py:157} INFO - Started process (PID=58492) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:55:44.576-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:55:44.577-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:55:44.577-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:55:44.607-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:55:44.607-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:55:44.607-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:55:44.607-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:55:44.607-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:55:44.670-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-11-09T20:57:53.758-0500] {processor.py:157} INFO - Started process (PID=58644) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:57:53.762-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T20:57:53.763-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:57:53.763-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:57:53.792-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:57:53.792-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T20:57:53.792-0500] {logging_mixin.py:154} INFO - [2023-11-09T20:57:53.792-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T20:57:53.792-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T20:57:53.854-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T21:00:09.365-0500] {processor.py:157} INFO - Started process (PID=58820) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:00:09.370-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:00:09.370-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:00:09.370-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:00:09.400-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:00:09.400-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:00:09.415-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:00:09.415-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:00:09.415-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:00:09.479-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2023-11-09T21:02:16.926-0500] {processor.py:157} INFO - Started process (PID=58990) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:02:16.931-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:02:16.931-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:02:16.931-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:02:16.960-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:02:16.960-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:02:16.960-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:02:16.960-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:02:16.960-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:02:17.023-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-11-09T21:04:18.208-0500] {processor.py:157} INFO - Started process (PID=59164) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:04:18.213-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:04:18.214-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:04:18.214-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:04:18.243-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:04:18.243-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:04:18.244-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:04:18.244-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:04:18.244-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:04:18.306-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-11-09T21:06:20.202-0500] {processor.py:157} INFO - Started process (PID=59324) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:06:20.211-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:06:20.211-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:06:20.211-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:06:20.270-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:06:20.269-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:06:20.270-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:06:20.270-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:06:20.270-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:06:20.417-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.216 seconds
[2023-11-09T21:08:17.553-0500] {processor.py:157} INFO - Started process (PID=59470) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:08:17.558-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:08:17.558-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:08:17.558-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:08:17.591-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:08:17.590-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:08:17.591-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:08:17.591-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:08:17.591-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:08:17.654-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2023-11-09T21:10:21.489-0500] {processor.py:157} INFO - Started process (PID=59639) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:10:21.494-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:10:21.495-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:10:21.495-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:10:21.530-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:10:21.529-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:10:21.530-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:10:21.530-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:10:21.530-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:10:21.604-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2023-11-09T21:12:21.462-0500] {processor.py:157} INFO - Started process (PID=59786) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:12:21.467-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:12:21.467-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:12:21.467-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:12:21.497-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:12:21.497-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:12:21.497-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:12:21.497-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:12:21.497-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:12:21.562-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2023-11-09T21:14:21.044-0500] {processor.py:157} INFO - Started process (PID=59933) to work on /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:14:21.049-0500] {processor.py:829} INFO - Processing file /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-09T21:14:21.049-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:14:21.049-0500] {dagbag.py:536} INFO - Filling up the DagBag from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:14:21.080-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:14:21.080-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-09T21:14:21.080-0500] {logging_mixin.py:154} INFO - [2023-11-09T21:14:21.080-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-09T21:14:21.081-0500] {processor.py:841} WARNING - No viable dags retrieved from /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-09T21:14:21.144-0500] {processor.py:179} INFO - Processing /Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
