[2023-11-10T17:35:05.953-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC manual__2023-11-10T22:34:57.827928+00:00 [queued]>
[2023-11-10T17:35:05.957-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC manual__2023-11-10T22:34:57.827928+00:00 [queued]>
[2023-11-10T17:35:05.957-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-10T17:35:05.964-0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): taskC> on 2023-11-10 22:34:57.827928+00:00
[2023-11-10T17:35:05.966-0500] {standard_task_runner.py:57} INFO - Started process 90199 to run task
[2023-11-10T17:35:05.970-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks', 'taskC', 'manual__2023-11-10T22:34:57.827928+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/excute_multiple_tasks.py', '--cfg-path', '/var/folders/84/qprfknln75z1qjwbnr6d2l2h0000gn/T/tmp8sigyv1l']
[2023-11-10T17:35:05.971-0500] {standard_task_runner.py:85} INFO - Job 30: Subtask taskC
[2023-11-10T17:35:05.990-0500] {task_command.py:416} INFO - Running <TaskInstance: executing_multiple_tasks.taskC manual__2023-11-10T22:34:57.827928+00:00 [running]> on host macbook-air-2.cogeco.local
[2023-11-10T17:35:06.019-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='executing_multiple_tasks' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T22:34:57.827928+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-10T22:34:57.827928+00:00'
[2023-11-10T17:35:06.020-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/84/qprfknln75z1qjwbnr6d2l2h0000gn/T
[2023-11-10T17:35:06.021-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK C has started!\nsleep 10\nexit 130 #fail\necho TASK C has ended!']
[2023-11-10T17:35:06.025-0500] {subprocess.py:86} INFO - Output:
[2023-11-10T17:35:06.027-0500] {subprocess.py:93} INFO - TASK C has started!
[2023-11-10T17:35:16.031-0500] {subprocess.py:97} INFO - Command exited with return code 130
[2023-11-10T17:35:16.043-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2023-11-10T17:35:16.050-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks, task_id=taskC, execution_date=20231110T223457, start_date=20231110T223505, end_date=20231110T223516
[2023-11-10T17:35:16.063-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 90199)
[2023-11-10T17:35:16.077-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-10T17:35:16.089-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
