[2023-11-19T19:00:10.921-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-19T19:00:10.925-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2023-11-19T19:00:10.925-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-19T19:00:10.932-0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): taskC> on 2023-11-19 00:00:00+00:00
[2023-11-19T19:00:10.934-0500] {standard_task_runner.py:57} INFO - Started process 47905 to run task
[2023-11-19T19:00:10.937-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks', 'taskC', 'scheduled__2023-11-19T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/excute_multiple_tasks.py', '--cfg-path', '/var/folders/84/qprfknln75z1qjwbnr6d2l2h0000gn/T/tmprwsh1b0j']
[2023-11-19T19:00:10.939-0500] {standard_task_runner.py:85} INFO - Job 90: Subtask taskC
[2023-11-19T19:00:10.958-0500] {task_command.py:416} INFO - Running <TaskInstance: executing_multiple_tasks.taskC scheduled__2023-11-19T00:00:00+00:00 [running]> on host macbook-air-2.cogeco.local
[2023-11-19T19:00:10.986-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='executing_multiple_tasks' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-19T00:00:00+00:00'
[2023-11-19T19:00:10.987-0500] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/84/qprfknln75z1qjwbnr6d2l2h0000gn/T
[2023-11-19T19:00:10.987-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK C has started!\nsleep 10\nexit 130 #fail\necho TASK C has ended!']
[2023-11-19T19:00:10.991-0500] {subprocess.py:86} INFO - Output:
[2023-11-19T19:00:10.994-0500] {subprocess.py:93} INFO - TASK C has started!
[2023-11-19T19:00:21.008-0500] {subprocess.py:97} INFO - Command exited with return code 130
[2023-11-19T19:00:21.027-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/az/anaconda3/envs/python38/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2023-11-19T19:00:21.033-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks, task_id=taskC, execution_date=20231119T000000, start_date=20231120T000010, end_date=20231120T000021
[2023-11-19T19:00:21.046-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 47905)
[2023-11-19T19:00:21.066-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T19:00:21.081-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
